### ISSUE TITLE
Also applicable to C925e

### ISSUE THREAD

**Issue by heikojansen** [MavChtz/C920e#1]
Not really an issue, just trying to make the following info publicly available:

I was unable to activate the microphone in my Logitech Webcam C925e on Linux.
It worked fine when connected to the Win 11 PC of a colleague, though.

When I found your script I decided to give it a chance because I had run out of other ideas on how to fix that behavior.

I slightly modified the code by setting `idProduct` to `0x085b` (based on `lsusb`) and after running it (on openSUSE Tumbleweed) the microphone started working for me, too.

Thanks for sharing the code!
- Heiko

**Comment by MavChtz** [comment]
Thanks for taking the time to test it against a new device.

I've added the product id for the C925e to the script and it should work without any modification now.
If you have the time, give it a try and let me know if it works as intended.

I am happy to hear that it helped you!
