### ISSUE TITLE
Everything works as expected 

### ISSUE THREAD

**Issue by marcosins** [MavChtz/C920e#6]
Hey, thank you for this script, it enabled the mic on my camera.

I'm just wondering how did you arrived at these addresses on `camera.ctrl_transfer` to enable the mic.

https://github.com/MavChtz/C920e/blob/e81d26b94cfc3b653f2edc5f0aee3da7cc34d227/C920e.py#L53

**Comment by MavChtz** [comment]
Hi, glad the script could help.

I found these values through trial and error with the help of Wireshark.
Capturing what was happening when the microphone was being turned off or on and observing what changed in their respective packets.

https://wiki.wireshark.org/CaptureSetup/USB
